### ISSUE TITLE
Getting list index out of range error

### ISSUE THREAD

**Issue by vivekaltruist** [dhruvramani/Terminal-on-FB-Messenger#11]
Hi, I am getting the following error:

```
Loading...

Traceback (most recent call last):
  File "/Users/labuser/main.py", line 187, in <module>
    init()
  File "/Users/labuser/main.py", line 170, in init
    replyButton=[x for x in driver.find_elements_by_tag_name('input') if x.get_attribute('value') == 'Reply'][0]
IndexError: list index out of range
```

**Comment by dhruvramani** [comment]
This is most probably dude to the page not loading properly, and thus selenium is not able to find the reply button. Please make sure your net connection is decent enough, and is the error occurring every time your run the program?

**Comment by vivekaltruist** [comment]
I ran it again and its working now.

**Comment by prk54** [comment]
Hi, I am getting the following error:
```
`Loading...

Traceback (most recent call last):
  File "/Users/labuser/main.py", line 187, in <module>
    init()
  File "/Users/labuser/main.py", line 170, in init
    replyButton=[x for x in driver.find_elements_by_tag_name('input') if x.get_attribute('value') == 'Reply'][0]
IndexError: list index out of range`
```

**Comment by dhruvramani** [comment]
Hey Prateek,

Yes you might be getting that error, as FB has changed the messaging
platform totally. I'll have to modify the script to adhere to the changes.
But currently I am off FB and don't plan to go back anytime soon.

Thanks,
Dhruv

On Apr 14, 2017 12:43 AM, "prateek lalwani" <notifications@github.com>
wrote:

Hi, I am getting the following error:

`Loading...

Traceback (most recent call last):
  File "/Users/labuser/main.py", line 187, in <module>
    init()
  File "/Users/labuser/main.py", line 170, in init
    replyButton=[x for x in driver.find_elements_by_tag_name('input')
if x.get_attribute('value') == 'Reply'][0]
IndexError: list index out of range`

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dhruvramani/Terminal-on-FB-Messenger/issues/11#issuecomment-293995410>,
or mute the thread

**Comment by Ravichandra-C** [comment]
Hi Dhruv,

Can I look into that and see if I can Fix it?

Regards,
Ravi.

**Comment by dhruvramani** [comment]
Hey Ravi,
Please feel free to work on it. I won't be getting time to work on it myself anytime soon.

**Comment by Ravichandra-C** [comment]
Awesome,

Thanks Mate :-)

Regards,
Ravi.
