### ISSUE TITLE
NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":"._2dpe._1ayn"}

### ISSUE THREAD

**Issue by yashwanthbabu** [dhruvramani/Terminal-on-FB-Messenger#3]
after logging in I am facing this error. Could you please look into that

**Comment by dhruvramani** [comment]
You are experiencing this because of a slow internet connection. This could be a race condition where the find_element is executing before it is present on the page. 

What you can do is add `driver.implicitly_wait(10)` before the line. 

If that doesn't work, follow up this [SO query](https://stackoverflow.com/questions/27112731/selenium-common-exceptions-nosuchelementexception-message-unable-to-locate-ele). 

Tell me if that doesn't work. I'll close the issue then.

**Comment by yashwanthbabu** [comment]
@dhruvramani This doesn't work for me. I have tried a lot. Can you have some other suggestion please?

**Comment by dhruvramani** [comment]
This problem is related to Selenium. Make sure you are using a stable version of Selenium. Could you like take a screenshot of it and post it here?

**Comment by yashwanthbabu** [comment]
<img width="1254" alt="screen shot 2016-02-11 at 8 09 09 pm" src="https://cloud.githubusercontent.com/assets/7446464/12979158/657fd7a8-d0fb-11e5-8ea1-0b0f15d72cd3.png">

Here is the screenshot of my error.

**Comment by dhruvramani** [comment]
Could you open up facebook on your browser, and make sure that the link to your profile on the profile button has the class I have used. If not, change it to the class which it has. I have attached an image of the button you are looking for. It's the one which says 'Dhruv'.

![screen shot 2016-02-11 at 8 14 02 pm](https://cloud.githubusercontent.com/assets/8494634/12983821/10b11fa6-d0fc-11e5-924b-b48fcede392b.png)

**Comment by dhruvramani** [comment]
Got it!
Add this line of the code `driver.set_window_size(1080,800)` just after initializer. I'll be adding it at next commit!

**Comment by dhruvramani** [comment]
Added it to the commit. Just sync and run it, I hope this will solve the problem
